---
- name: DEPLOY RabbitMQ Cluster
  hosts: rmq_test
  become: true

#  pre_tasks:

#    - name: update all packages
#      dnf:
#        name: "*"
#        state: latest

  roles:

    - etc_hosts
    - rabbitmq
    - keepalived
    - haproxy
